---
- name: Remove unneeded packages
  yum: >
    name={{item}}
    state=absent
  with_items:
    - gtk2
    - libX11
    - hicolor-icon-theme
    - avahi
    - freetype
    - bitstream-vera-fonts
    - cpp
    - kernel-devel
    - kernel-headers

# No equivalent ansible yum module option
- name: Clean yum
  command: yum clean all

- name: Clean Ruby Gems
  file:
    path: /tmp/rubygems-*
    state: absent
