---
# Configure VirtualBox VM Image

- name: Install VirtualBox Guest Additions
  include: guest-additions.yml

- name: Configure VM Networking
  include: networking.yml

- name: Clean Up
  include: cleanup.yml